name: Build

permissions:
  contents: write

on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          # Linux config
          - name: linux-amd64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            command: cross
          # Windows
          - name: win-amd64
            runner: windows-latest
            target: x86_64-pc-windows-msvc
            command: cargo
          # MacOs Arm
          - name: macos-arm64
            runner: macos-latest
            target: aarch64-apple-darwin
            command: cargo
 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
 
      # Only install cross if we need it
      # Install via cargo-binstall which I found faster
      - name: Install Cross
        if: matrix.command == 'cross'
        shell: bash
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall --no-confirm cross
 
      - name: Build Binary
        run: ${{ matrix.command }} build --lib --release 

      - name: List directory
        run: ls target/release
      
      - name: Upload Macos binary
        if: runner.os == 'MacOS'
        uses: actions/upload-artifact@v3
        with:
          name: libprinter_bindings.dylib
          path: target/release/libprinter_bindings.dylib

      - name: Release MacOS binary Zip
        if: runner.os == 'MacOS'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: denyncrawford/deno-printers
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/libprinter_bindings.dylib
          tag: ${{ github.event.release.tag_name }}
          asset_name: libprinter_bindings.dylib
          overwrite: true
          
      - name: Upload Linux binary
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: libprinter_bindings.so
          path: target/release/libprinter_bindings.so

      - name: Release Linux binary
        if: runner.os == 'Linux'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: denyncrawford/deno-printers
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/libprinter_bindings.so
          tag: ${{ github.event.release.tag_name }}
          asset_name: libprinter_bindings.so
          overwrite: true

      - name: Upload Windows binary
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: printer_bindings.dll
          path: target/release/printer_bindings.dll

      - name: Release Windows binary
        if: runner.os == 'Linux'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: denyncrawford/deno-printers
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/printer_bindings.dll
          tag: ${{ github.event.release.tag_name }}
          asset_name: printer_bindings.dll
          overwrite: true
